# Generated by Django 5.1 on 2024-08-20 10:15

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=150)),
                ("consumption_date", models.DateTimeField()),
                ("quantity", models.FloatField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Requisition1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emanating_dept",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "requesting_officer",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=500,
                        null=True,
                        verbose_name="In_Charge",
                    ),
                ),
                ("hod_consent", models.CharField(default="", max_length=30)),
                (
                    "action_by",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "manager",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("date_submitted", models.DateTimeField(blank=True, null=True)),
                ("date_received", models.DateTimeField(blank=True, null=True)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "request_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workorder1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(default="", max_length=50)),
                ("receiving_unit", models.CharField(default="", max_length=50)),
                ("date_received", models.DateField(verbose_name=datetime.date.today)),
                (
                    "completion_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("machine", models.CharField(default="", max_length=250)),
                (
                    "manager",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
