# Generated by Django 4.2.3 on 2024-06-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='equipment',
        ),
        migrations.AddField(
            model_name='workorder',
            name='machine',
            field=models.CharField(default='', max_length=250),
        ),
    ]
