# Generated by Django 5.1 on 2024-08-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="reason_delay",
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name="requisition",
            name="requisition_no",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
    ]
