# Generated by Django 4.2.3 on 2024-07-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_workorder_equipment_workorder_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='last_service',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, default='', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='next_service',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
