# Generated by Django 4.2.3 on 2024-07-16 12:21

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_todolist_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDoneList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkDoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('name', models.TextField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(default=myapp.models.one_week_hence)),
                ('cost', models.CharField(max_length=150)),
                ('item_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.todolist')),
            ],
        ),
    ]
