# Generated by Django 4.2.3 on 2024-07-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_workdonelist_workdoneitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdoneitem',
            name='item_list',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='status',
        ),
        migrations.AddField(
            model_name='workdoneitem',
            name='work_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.workorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
