# Generated by Django 4.2.3 on 2024-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_workdoneitem_work_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
